### ISSUE TITLE
Add the correspondent fgile on /usr/share/pam-configs

### ISSUE THREAD

**Issue by mhalano** [Yubico/pam-u2f-dpkg#4]
Any PAM module has (or should have) a file on /usr/share/pam-configs/ which allows to enable/disable quickly using the 'pam-auth-update' command. The repository pam-yubico-dpkg already has the file and this repository should have too.

**Comment by a-dma** [comment]
ping @jas4711

**Comment by pratheekrebala** [comment]
Just wanted to bump this @LDVG. Being able to use `pam-auth-update` would make this much easier to configure/disable.

Thank you!

**Comment by LDVG** [comment]
> Just wanted to bump this @LDVG. Being able to use `pam-auth-update` would make this much easier to configure/disable.

Hi, @pratheekrebala! Thanks for bringing this to my attention. I'll have a look when time permits.

**Comment by pratheekrebala** [comment]
Hi @LDVG,

Thank you for working on this! Apologies about the delay. I can test this and circle back in the next few days.
